### ISSUE TITLE
Microsoft VBScript runtime error

### ISSUE THREAD

**Issue by Mama1uigi** [lemasato/Non-Steam-Overlay-Manager#2]
![help](https://user-images.githubusercontent.com/33592956/32697075-d44f6414-c744-11e7-819e-02d4a0faf65f.PNG)
please help what do i do

**Comment by Mama1uigi** [comment]
i worked around it by manually putting it in in the ini file but now the game wont start after i play from the launcher

**Comment by lemasato** [comment]
Yeah, I've had issues as well when running this on W10.

I've been working on an alternative, and it seems to be running just fine. Though, it needs some testings to make sure it works correctly on different games and W7/W10. I would like to add some GUI to make things much (much) easier.

Can't really say when I'll be out. Haven't had much time lately, and I have to do multiple things on my other stuffs: [POE Trades Companion](https://github.com/lemasato/POE-Trades-Companion), [Game Vivifier](https://github.com/lemasato/Game-Vivifier), a new thing for Battle.net, and this one.

So yeah. I think I'll prioritize the new BNet thing since it's almost done. Then get working on this.

**Comment by lemasato** [comment]
Great. I have the idea set up and will get working on it now.
Would you agree testing it out once it's ready for use?

**Comment by lemasato** [comment]
Well, it's out: https://github.com/lemasato/Non-Steam-Overlay-Manager/releases
Feel free to try it out. Will be closing this issue for now, but if you have any question, I'll be glad to answer.
