### ISSUE TITLE
Error with script

### ISSUE THREAD

**Issue by yoongjun** [lemasato/Non-Steam-Overlay-Manager#4]
When I try to launch the game via the launcher, the script instantly kills the game after the game instance is detected.

It'll be like:

Launch on steam > [1/5] starting launcher > [2/5] waiting for launcher to start game

Then once I hit start game on the launcher the script instantly goes through steps 3/4/5 and killing it at the end.

**Comment by lemasato** [comment]
I've got a new beta comming up.  
Should be done by Tuesday.

**Comment by lemasato** [comment]
Hey there,  
NSO Manager v0.1 has been released. You can download it on the [releases](https://github.com/lemasato/Non-Steam-Overlay-Manager/releases) tab.  

I will be closing this issue since the old vbs script is no longer supported.  
Though, if you have any question, feel free to respond or open a new one!
