### ISSUE TITLE
Error - Windows Store Games

### ISSUE THREAD

**Issue by RuldBaz** [lemasato/Non-Steam-Overlay-Manager#8]
Any idee what I have to do?
http://prntscr.com/iggor6

**Comment by lemasato** [comment]
Could you provide the settings for the profile you are trying to run?
`Documents\AutoHotkey\NSO Manager\Profiles.ini`

**Comment by RuldBaz** [comment]
https://ufile.io/j937l

**Comment by lemasato** [comment]
Should be working just fine.
From the first screenshot, it looks like it cannot fine the file: `D:\Shortcuts\Sea of Thieves.lnk`
Make sure the file exists and if it does, then make sure it points to the right file (Right click > Properties > See the "Target:" field)

**Comment by RuldBaz** [comment]
The file exist, when I open it by itself without the program it works.
It is a windows store game, maybe that is the problem..

**Comment by lemasato** [comment]
Oops, yeah. That's the reason.
From what I can tell, WinStore games do not point to a specific executable but rather some kind of "application ID". Though, the games do have their own process in the task manager, so I guess I could work around that.

**Comment by RuldBaz** [comment]
It would be amaizing if you could do that:D

**Comment by lemasato** [comment]
Okay, so I tried with Zoo Tycoon and from what I could find, the game window's process is not the same as the game executable's process.
Game executable process: MSTycoon.final.exe
Game's window process: ApplicationFrameHost.exe

This means that even if we were to allow the game executable to use the NSO Overlay hotkey, it wouldn't work as the actual game window does not share the same process.

I could make you some "workaround" until I get to work on improvements if you'd like.
All I would need is the game executable (you can get this from the task manager)

**Comment by RuldBaz** [comment]
Game executable process: SoTGame.exe
If possible I would have another windows store game Forza Horizon 3
Here is the Game executable in case you could do it too: forza_x64_release_final.exe

**Comment by lemasato** [comment]
Okay. I'll have to finish and test the side app in a few hours, then I'll post it here.

**Comment by RuldBaz** [comment]
Ok ty

**Comment by lemasato** [comment]
(Took a bit longer due to some unexpected issues)

I was intending on releasing it as a separate app, but decided to include it in NSO Manager.
Make sure to update to the latest version, then run NSO Manager once so that the assets are extracted.

To set it up, head to this section of the README: [it-doesnt-work-for-my-winstore-app-game-what-do-i-do](https://github.com/lemasato/Non-Steam-Overlay-Manager/blob/master/README.md#it-doesnt-work-for-my-winstore-app-game-what-do-i-do)

**Comment by RuldBaz** [comment]
After I run the file from steam I always have to validate? or only the first time? cause for me does it all the time to validate the game.
And the second problem that i found is that after I run the game and enter on it, both the NSO manager and the workaround close/crash.

**Comment by lemasato** [comment]
You have to choose which game every time.  
Though, the "point shortcut, point executable" steps should only appear once.

It is possible that NSO Manager and the side-app workaround close because the game process was not found. In that case, I would recommend to choose "Do nothing" instead and see it it works that way.

**Comment by RuldBaz** [comment]
Ok so when I selected "Do nothing" the game didnt start at all.
For the part when you have to choose always to validate I found a way to put in parameters /Game="Forza Horizon 3"
Everything works fine in windowed mode, but once I go in fullscreen mode , the workaround stops and the overlay doesnt work anymore, it works only in windowed mode

**Comment by lemasato** [comment]
When using the "Do nothing" option, you have to start your game manually.
This option is meant to be used for games which are not pre-included in the options.

Also yes, the /Game parameter does work, but NSO will not exit automatically upon game closure.

NSO is not meant to work in Fullscreen. You have to use Windowed or Borderless modes.

**Comment by RuldBaz** [comment]
Ok ty

**Comment by lemasato** [comment]
Hi there,
[0.2.6](https://github.com/lemasato/Non-Steam-Overlay-Manager/releases/tag/0.2.6) has been released.

You can now simply add the game's shortcut, and it will work.
Though, as specified in the patch notes, will make NSO Manager unable to close itself automatically upon game closure since we can't retrieve the game's process name.
